<?php

namespace app\controllers;
use app\models\Users;
use Yii;
use  yii\web\Session;
//后台页面
class AdminController extends BaseController
{
    public $layout=false;
    public $defaultAction='home';
    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionLogin(){
        return $this->render('login');
    }
    //判断登录
    public function actionPro(){
        if(Yii::$app->request->isPost){
            $username = Yii::$app->request->post('username');
            $userpwd = Yii::$app->request->post('userpwd');
            $users = New Users();
            $res=$users->getDataName($username,md5($userpwd));
            if($res){
                $session = Yii::$app->session;
                $session->set('sedumes_user', md5('sedumes'));
                $session->set('sedumes_name', $username);
                return $this->redirect('/admin/home');
            }else{
                return $this->redirect('/admin/login');
            }
        }else{
            return $this->redirect('/admin/login');
        }
    }
    public function actionHome(){
        $session = Yii::$app->session;
        $user_id = $session->get('sedumes_user');
        if($user_id){
            return $this->render('home');
        }else{
            return $this->redirect('/admin/login');
        }
    }

    /**
     * 退出登录
     */
    public function actionLogout(){
        Yii::$app->session->set('sedumes_user','');
        Yii::$app->session->set('sedumes_name','');
        return $this->redirect('/admin/login');
    }
}