<?php

namespace app\controllers;

/**
 * Class HomeUserController
 * @package app\controllers
 * 前台用户管理
 */
class HomeUserController extends BaseController
{
    public $layout=false;

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        echo 111;die;
        return $this->render('admin/userlist');
    }
}